services:
  postgres:
    networks:
      - internal
      - local-access
    ports:
      - 127.0.0.1:${POSTGRES_HOST_PORT:-5432}:5432

  valkey:
    networks:
      - internal
      - local-access
    ports:
      - 127.0.0.1:${VALKEY_HOST_PORT:-6379}:6379

networks:
  local-access:
    name: ${COMPOSE_PROJECT_NAME:-votaciones}_local_access
