export type EligibilityErrorCode =
  | 'ELIGIBLE_VOTER_NOT_FOUND'
  | 'ELIGIBLE_VOTER_INACTIVE'
  | 'CREDENTIAL_NOT_FOUND'
  | 'CREDENTIAL_ALREADY_REGISTERED'
  | 'CREDENTIAL_REVOKED'
  | 'INVALID_IDENTITY_COMMITMENT'
  | 'ELIGIBILITY_SNAPSHOT_NOT_FOUND'
  | 'ELIGIBILITY_SNAPSHOT_NOT_BUILDING'
  | 'ELIGIBILITY_SNAPSHOT_FROZEN'
  | 'ELIGIBILITY_SNAPSHOT_CAPACITY_EXCEEDED'
  | 'ELIGIBILITY_SNAPSHOT_DUPLICATE_LEAF'
  | 'ELIGIBILITY_SNAPSHOT_EMPTY'
  | 'ELIGIBILITY_CRYPTOGRAPHY_NOT_CONFIGURED'
  | 'ELIGIBILITY_CONCURRENT_MODIFICATION'
  | 'INVALID_ELIGIBLE_VOTER';

export class EligibilityDomainError extends Error {
  constructor(
    readonly code: EligibilityErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'EligibilityDomainError';
  }
}
