export const ELIGIBLE_VOTER_REPOSITORY = Symbol('ELIGIBLE_VOTER_REPOSITORY');
export const ELECTORAL_CREDENTIAL_REPOSITORY = Symbol('ELECTORAL_CREDENTIAL_REPOSITORY');
export const ELIGIBILITY_SNAPSHOT_REPOSITORY = Symbol('ELIGIBILITY_SNAPSHOT_REPOSITORY');
export const MERKLE_TREE_BUILDER = Symbol('MERKLE_TREE_BUILDER');
